version: "3.8"

services:
  fanhist:
    build: .
    # or: image: <your-dockerhub-username>/fanhist:latest
    container_name: fanhist
    restart: unless-stopped
    ports:
      - "8181:8081"
    volumes:
      - ./data:/data
